---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "QYMBzZgi4sb7lRQltyQ8bOcTu7+DDzbyLHkxvV+vVRCQVQcVj/7xUHjPRM0wB6+PZ5W+NcoEXl0EszZ/PtTTUGXCK1UjSNeQ/g2QGJpV8wacgjAl1N8x4p0u/oXt3UoS/oumfleUC8O+ufsiqbPxfMdA+9RzTUVMIwwhKce/Z1yjcnGKq6gLerK4cDg5AMzJG8GzaEWVfcC6TaQf3ZvoGXR30dHjUocj6jcUTtxfWiTBA+GmK7U7EAH2FU2O8Z8yhGwAEN6fiSI83PRw9K12HKwzEwcZutu7/a1UjIvfHPLy/HbAGn38KHPb77IhpBy69VlKlVxELqp40B9AnGHIPfsBiExjRrFPCBchRzKMpd3yAdeNQHLnsYkUjHa+byib4AkHlNPjdxoyI2gIFFF95ClKr7uULtJVZm2z1TP3M5P2UDJ1Lg/cjWitxHhZnCFACMLwPMa+s0jmk9YrYGOpeL7prtLMqQsUW/IfbsnBQH98pxCQlB/XvLQ4Aw89jbou2MkknCHdplB6lnsDn2Ml6izgmdSUdxt5gPeCYZnO+2pkmV90ihBYIdazgyZ7vKqhmgr4OUxmWtGMcnpmLmKl5W0MSE02agbKmO9H86+4nBmm6RIIikPrEWr8TuBVSU8nulm19s3zoP7r8mrOGuSVtBU2v9aa6AEZeELcSfaReKw="
  email: false
