---
sudo: required
language: python
services: docker

env:
  - version=">=2.6,<2.7" distro="alpine-latest"
  - version="" distro="alpine-latest"
  - version="devel" distro="alpine-latest"
  - version=">=2.6,<2.7" distro="alpine-edge"
  - version="" distro="alpine-edge"
  - version="devel" distro="alpine-edge"
  - version=">=2.6,<2.7" distro="archlinux"
  - version="" distro="archlinux"
  - version="devel" distro="archlinux"
  - version=">=2.6,<2.7" distro="centos-6"
  - version="" distro="centos-6"
  - version="devel" distro="centos-6"
  - version=">=2.6,<2.7" distro="centos-latest"
  - version="" distro="centos-latest"
  - version="devel" distro="centos-latest"
  - version=">=2.6,<2.7" distro="debian-latest"
  - version="" distro="debian-latest"
  - version="devel" distro="debian-latest"
  - version=">=2.6,<2.7" distro="debian-stable"
  - version="" distro="debian-stable"
  - version="devel" distro="debian-stable"
  - version=">=2.6,<2.7" distro="debian-unstable"
  - version="" distro="debian-unstable"
  - version="devel" distro="debian-unstable"
  - version=">=2.6,<2.7" distro="fedora-latest"
  - version="" distro="fedora-latest"
  - version="devel" distro="fedora-latest"
  - version=">=2.6,<2.7" distro="fedora-rawhide"
  - version="" distro="fedora-rawhide"
  - version="devel" distro="fedora-rawhide"
  - version=">=2.6,<2.7" distro="opensuse-leap"
  - version="" distro="opensuse-leap"
  - version="devel" distro="opensuse-leap"
  - version=">=2.6,<2.7" distro="opensuse-tumbleweed"
  - version="" distro="opensuse-tumbleweed"
  - version="devel" distro="opensuse-tumbleweed"
  - version=">=2.6,<2.7" distro="ubuntu-artful"
  - version="" distro="ubuntu-artful"
  - version="devel" distro="ubuntu-artful"
  - version=">=2.6,<2.7" distro="ubuntu-latest"
  - version="" distro="ubuntu-latest"
  - version="devel" distro="ubuntu-latest"
  - version=">=2.6,<2.7" distro="ubuntu-devel"
  - version="" distro="ubuntu-devel"
  - version="devel" distro="ubuntu-devel"

matrix:
  fast_finish: yes
  allow_failures:
    - env: version=">=2.6,<2.7" distro="alpine-edge"
    - env: version="" distro="alpine-edge"
    - env: version="devel" distro="alpine-edge"
    - env: version="devel" distro="alpine-latest"
    - env: version="devel" distro="archlinux"
    - env: version="devel" distro="centos-6"
    - env: version="devel" distro="centos-latest"
    - env: version="devel" distro="debian-latest"
    - env: version="devel" distro="debian-stable"
    - env: version=">=2.6,<2.7" distro="debian-unstable"
    - env: version="" distro="debian-unstable"
    - env: version="devel" distro="debian-unstable"
    - env: version="devel" distro="fedora-latest"
    - env: version=">=2.6,<2.7" distro="fedora-rawhide"
    - env: version="" distro="fedora-rawhide"
    - env: version="devel" distro="fedora-rawhide"
    - env: version="devel" distro="opensuse-leap"
    - env: version="devel" distro="opensuse-tumbleweed"
    - env: version="devel" distro="ubuntu-artful"
    - env: version=">=2.6,<2.7" distro="ubuntu-devel"
    - env: version="" distro="ubuntu-devel"
    - env: version="devel" distro="ubuntu-devel"
    - env: version="devel" distro="ubuntu-latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "fRRfNM9J6RirH9ls358R3X42dmq7DibWLKikPXRu0oWffiTLlSt/O9yG5Wl0z/xxcCPQW8QHW7TAGHY/5x+apIQ2zkzti9v+5bBCekKc+Q2ImDVOwIoU8IXUNJOZIeD4sdnpgIytqb3sNG6HbM92/4Mmy5k1E+NraQ82G60sUHcabdqvsCJdGCSpZ7V1CA3AO5WffO1xVk5r1RjyZaDOmeH3PEUmNFfrNoxUkSkUSsfw3JhB1MOzyQAGkmqdjuLa5osVMN+vs/ZHKCJLFtv+Hhv+D6N8axW2IB6+9+1Y5+4NUTHz2VL2HUBAu49Qo/RU9+nFfUNOLeCnA1Ri1/Rf10Xa85pcI0xhwmudJTRG9sq5ICgg9VHRBVcZj/6Q0Klr2mRAFv0C1EHDKeUy79QHoCL0y1Ofk+aDd+lSaotadDzG7Z4f4wOgya+PmfAFPQ3/CWYle31bGa1ddv/PlzvELhBzd+kh3EaE+DYgC6Lnt7YHdkwz3v8Offah8EeX8yvxiRKvOKaWvKPvYt5hKhDi5VTM5gAQKw5nF65Uz7OZ/EMUR2jopUlxq+9v8Byx1ZJfPo7tFLtPjy1NG95KzT+PUrsFhNz2/8Eb4ChqzN03omNmQN8DvqWOXV+QBStIpuVaGDJQ52lbgSfYkgvIyaJBqeoQXnRpfLJ7zuAfpbJH0wI="
  email: false
