---
# tasks file for mysql
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mysql_packages }}"

- name: configure software
  ini_file:
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    section: mysqld
    option: bind-address
    value: "{{ mysql_bind_address }}"
  notify:
    - restart mysql server

- name: start and enable software
  service:
    name: "{{ mysql_service }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"

- name: create databases
  mysql_db:
    name: "{{ item.name }}"
    state: present
    encoding: "{{ item.encoding | default(omit) }}"
    collation: "{{ item.collation | default(omit) }}"
  with_items:
    - "{{ mysql_databases }}"
  when:
    - mysql_databases is defined
    - ansible_virtualization_type != "docker"

- name: create users
  mysql_user:
    name: "{{ item.name }}"
    state: present
    password: "{{ item.password | default (omit) }}"
    priv: "{{ item.priv | default (omit) }}"
    host: "{{ item.host | default (omit) }}"
  with_items:
    - "{{ mysql_users }}"
  when:
    - mysql_users is defined
    - ansible_virtualization_type != "docker"
