---
# tasks file for mysql
- name: install mysql
  package:
    name: "{{ mysql_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
          | default(mysql_packages[ansible_distribution]
          | defaukt(mysql_packages['default'])) }}"
    state: "{{ mysql_package_state }}"

- name: configure mysql
  ini_file:
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    section: mysqld
    option: bind-address
    value: "{{ mysql_bind_address }}"
  notify:
    - restart mysql server

- name: start and enable mysql
  service:
    name: "{{ mysql_service[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
          | default(mysql_service[ansible_distribution]
          | default(mysql_service['default'])) }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"

- name: create databases
  mysql_db:
    name: "{{ item.name }}"
    state: present
    encoding: "{{ item.encoding | default(omit) }}"
    collation: "{{ item.collation | default(omit) }}"
  with_items:
    - "{{ mysql_databases }}"
  when:
    - mysql_databases is defined
    - ansible_virtualization_type != "docker"

- name: create users
  mysql_user:
    name: "{{ item.name }}"
    state: present
    password: "{{ item.password | default (omit) }}"
    priv: "{{ item.priv | default (omit) }}"
    host: "{{ item.host | default (omit) }}"
  with_items:
    - "{{ mysql_users }}"
  when:
    - mysql_users is defined
    - ansible_virtualization_type != "docker"
