---
# tasks file for mysql
- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mysql_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(mysql_packages[ansible_distribution]
      | default(mysql_packages['default'] )) }}"

- name: install modules
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mysql_pip_modules[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(mysql_pip_modules[ansible_distribution]
      | default(mysql_pip_modules['default'] )) }}"

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ mysql_services[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(mysql_services[ansible_distribution]
      | default(mysql_services['default'] )) }}"
  when:
    - ansible_virtualization_type != "docker"
