---
- name: set root password
  block:
    - name: try mysqladmin
      ansible.builtin.command: mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"
  rescue:
    - name: fallback to mysqladmin
      ansible.builtin.command: mysqladmin -u root password {{ mysql_root_password }}
  become: yes
  become_user: "{{ mysql_user }}"
