---
# handlers file for mysql
- name: restart mysql server
  service:
    name: "{{ mysql_service[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
          | default(mysql_service[ansible_distribution]
          | default(mysql_service['default'])) }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
