---
# handlers file for mysql

- name: restart mysql server
  ansible.builtin.service:
    name: "{{ mysql_service }}"
    state: restarted
  when:
    - not ansible_check_mode | bool

- name: set root password
  ansible.builtin.include_tasks: tasks/set_root_password.yml
