---
- name: Converge
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-mysql

  tasks:
    - name: Create database
      mysql_db:
        name: bobdata
        state: present

    - name:
      mysql_user:
        name: bob
        password: 12345
        priv: '*.*:ALL'
        state: present
