---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: ansible-role-mysql

  tasks:
    - name: Create database
      mysql_db:
        name: bobdata
        state: present

    - name:
      mysql_user:
        name: bob
        password: 12345
        priv: '*.*:ALL'
        state: present
