---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mysql-archlinux
    image: base/archlinux
  - name: mysql-alpine-3.6
    image: alpine:3.6
  - name: mysql-alpine-3.7
    image: alpine:3.7
  - name: mysql-centos-6
    image: centos:6
  - name: mysql-centos-7
    image: centos:7
  - name: mysql-debian-jessie
    image: debian:jessie
  - name: mysql-debian-stretch
    image: debian:stretch
  - name: mysql-debian-buster
    image: debian:buster
  - name: mysql-fedora-26
    image: fedora:26
  - name: mysql-fedora-27
    image: fedora:27
  - name: mysql-opensuse-42.2
    image: opensuse:42.2
  - name: mysql-opensuse-42.3
    image: opensuse:42.3
  - name: mysql-ubuntu-artful
    image: ubuntu:artful
  - name: mysql-ubuntu-bionic
    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: 'flake8'
