---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-mysql
      mysql_databases:
        - name: my_db
          encoding: utf8
          collation: utf8_bin
        - name: my_db
          state: dump
          target: /tmp/my_db.mysql
      mysql_users:
        - name: my_user
          password: my_pass
          priv: "my_db.*:ALL"

  post_tasks:
    - name: try root account
      mysql_db:
        name: my_test
        state: present
        login_user: root
        login_password: s3Cur31t4.
