---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  post_tasks:
    - name: try root account
      mysql_db:
        name: my_test
        state: present
        login_user: root
        login_password: s3Cur31t4.
