---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '40 0 13 * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: molecule
        uses: robertdebock/molecule-action@1.2.8
        with:
          entrypoint: /usr/local/bin/molecule
          args: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "amazonlinux"
            tag: "latest"
          - image: "debian"
            tag: "latest"
          - image: "debian"
            tag: "unstable"
          - image: "centos"
            tag: "7"
          - image: "centos"
            tag: "latest"
          - image: "fedora"
            tag: "30"
          - image: "fedora"
            tag: "latest"
          - image: "fedora"
            tag: "rawhide"
          - image: "opensuse"
            tag: "latest"
          - image: "ubuntu"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: remove mysql
        run: sudo apt-get remove -y --purge mysql-client libmysqlclient-dev mysql-server mssql-tools unixodbc-dev
      - name: autoremove
        run: sudo apt autoremove
      - name: molecule
        uses: robertdebock/molecule-action@1.2.8
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
          options: "--parallel all"
        env:
          TOX_PARALLEL_NO_SPINNER: 1
